// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqDVQrZznnKeTTxhJHm9Hl0-rKxW7iwHk',
    appId: '1:975727897994:web:5783d77527cbc456232c73',
    messagingSenderId: '975727897994',
    projectId: 'khap-96581',
    authDomain: 'khap-96581.firebaseapp.com',
    storageBucket: 'khap-96581.appspot.com',
    measurementId: 'G-X84187M4YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEs0rAtAc8y1uaRBY3WDYJFPvsT3Y2vUI',
    appId: '1:975727897994:android:005c304868a6b744232c73',
    messagingSenderId: '975727897994',
    projectId: 'khap-96581',
    storageBucket: 'khap-96581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb0KA7A17MYbdXF_DstLiAgdj6P6ieDl0',
    appId: '1:975727897994:ios:86ab1926507c927d232c73',
    messagingSenderId: '975727897994',
    projectId: 'khap-96581',
    storageBucket: 'khap-96581.appspot.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );

}